#!/usr/bin/env node

global.FOAM_FLAGS = {
  android: true,
  debug: true,
  java: true,
  js: true,
  node: true,
  swift: true,
};

require('../src/foam.js');
require('../src/foam/nanos/nanos.js');

foam.classloader.NodeJsModelExecutor.create().fromArgs(process.argv.slice(2)).execute();
