if ( typeof window !== 'undefined' ) global = window;

FOAM_FILES([
  { name: "foam/core/poly" },
  { name: "foam/core/lib" },
  { name: "foam/core/stdlib" },
  { name: "foam/core/events" },
  { name: "foam/core/Context" },
  { name: "foam/core/Boot" },
  { name: "foam/core/FObject" },
  { name: "foam/core/Model" },
  { name: "foam/core/Property" },
  { name: "foam/core/Method" },
  { name: "foam/core/Boolean" },
  { name: "foam/core/AxiomArray" },
  { name: "foam/core/EndBoot" },
  { name: "foam/core/Script" },
  { name: "foam/core/FObjectArray" },
  { name: "foam/core/Constant" },
  { name: "foam/pattern/Faceted" },
  { name: "foam/core/types" },
  { name: "foam/core/Topic" },
  { name: "foam/core/InnerClass" },
  { name: "foam/core/InnerEnum" },
  { name: "foam/core/Implements" },
  { name: "foam/core/ImportsExports" },
  { name: "foam/core/Listener" },
  { name: "foam/core/Requires" },
  { name: "foam/core/Slot" },
  { name: "foam/core/Proxy" },
  { name: "foam/core/Promised" },
  { name: "foam/core/Interface" },
  { name: "foam/core/Exception" },
  { name: "foam/core/ContextMethod" },
  { name: "foam/core/Window" },
  { name: "foam/classloader/ClassLoader" },
  { name: "foam/core/Argument" },
  { name: "foam/core/MultiMethod" },
  { name: "foam/core/debug", flags: ['debug'] },
  { name: "foam/pattern/Singleton" },
  { name: "foam/pattern/Multiton" },
  { name: "foam/core/Enum" },
  { name: "foam/core/JSON" },
  { name: "foam/core/Action" },
  { name: "foam/core/Serializable" },
  { name: "foam/mlang/order/Comparator" },
  { name: "foam/mlang/mlang" },
  { name: "foam/dao/Sink" },
  { name: "foam/dao/ArraySink" },
  { name: "foam/dao/DAO" },
  { name: "foam/dao/AbstractDAO" },
  { name: "foam/dao/DAOProperty" },
  { name: "foam/dao/Relationship" },
  { name: "foam/dao/daoUtils" },
  { name: "foam/apploader/ModelRefines" },
  { name: "foam/apploader/ClassLoader" },
  { name: "foam/apploader/SubClassLoader" },
  { name: "foam/apploader/WebModelFileFetcher", flags: ['web'] },
  { name: "foam/apploader/NodeModelFileFetcher", flags: ['node'] },
  { name: "foam/apploader/ModelFileDAO" },
  { name: "foam/apploader/WebModelFileDAO", flags: ['web'] },
  { name: "foam/apploader/NodeModelFileDAO", flags: ['node', 'debug'] },
  { name: "foam/apploader/ClassLoaderContext" },
  { name: "foam/net/web/HTTPResponse" },
  { name: "foam/net/web/HTTPRequest" },
  { name: "foam/net/web/BaseHTTPRequest" },
  { name: "foam/net/web/WebSocket" },
  { name: "foam/net/web/WebSocketService" },
  { name: "lib/net" },
]);
